### PR TITLE
Port to minecraft 1.12

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This version also requires The baubles api and the wearable backpacks api from their repos, as they are not on mavens that I could find.

### CODE REVIEW

**Comment by FiveEYZ** [comment]
will this happen in a near future? <3 
this is by far the best grave mod and the only one that have a restore cmd

**Comment by M4thG33k** [comment]
I've done some changes to the mod between when this was posted and now - I'll look into this later this week, if time permits.

**Comment by ghost** [comment]
Might I ask how it goes.
Would love to use ToombManyGraves2 for my WIP modpack, which is targeted to 1.12.1.

**Comment by Shadows-of-Fire** [comment]
If anyone wants this as it is, there is this github release: https://github.com/Shadows-of-Fire/TombManyGraves2/releases

**Comment by Shadows-of-Fire** [comment]
I would like to refrain from doing it, but i may consider creating it as a separate project since m4thg33k has been so inactive.

**Comment by M4thG33k** [comment]
Sorry, guys, I started a new job recently and time is escaping me. I'll really try to work on updates this weekend!

**Comment by Shadows-of-Fire** [comment]
Well, there we go, merge conflicts gone.  Should make this easy.  Still requires a baubles deobf and a wearable backpacks deobf to build tho.  Cosmetic armor support should be able to be reimplemented now, but Cyberware appears to be dead.

**Pull request merged**
